basePath: /
info:
  contact: {}
  description: test swag
  title: Example API
  version: "1.0"
paths:
  /order/{id}:
    get:
      consumes:
      - application/json
      description: Get Order by ID
      parameters:
      - description: Order ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: Get Order by id
      tags:
      - Order
swagger: "2.0"
